docker:
  image: stono/testyomesh
  tag: latest
  pullPolicy: IfNotPresent

config:
  # How many worker threads should we spawn to make requets
  workerThreadCount: 30
  # How many simpleServices should we spawn
  simpleServices: 3
  # How many replicas of each simple service?
  simpleServiceReplicas: 1

  # How many loadTest instances?
  loadTestReplicas: 2

  # Which http methods should we test
  httpMethods:
  - 'GET'
  - 'HEAD'
  - 'POST'
  - 'PUT'
  - 'PATCH'
  - 'DELETE'

  # Which paths should we hit on the simpleService
  httpPaths:
  - '/instant'
  - '/delayed'

  # Which status codes should we request back from downstream calls
  statusCodes:
  - 200
  - 201
  - 202
  - 204
