docker:
  image: stono/testyomesh
  tag: latest
  pullPolicy: IfNotPresent

config:
  # How many worker threads should we spawn to make requets
  workerThreadCount: 30
  # How many simpleServices should we spawn
  simpleServices: 3
  # How many replicas of each simple service?
  simpleServiceReplicas: 1

  # How many loadTest instances?
  loadTestReplicas: 2
