apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: testyomesh
    component: testyomesh
  name: load-tester
rules:
  - apiGroups:
      - ''
    resources:
      - configmaps
    verbs:
      - list
      - get
