apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: testyomesh
    component: operator
  name: operator
data:
{{- range $key, $val := .Values.config }}
  {{ $key }}: {{ (toString $val)  | quote}}
{{- end }}
