apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: testyomesh
    component: operator
  name: operator
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - list
      - get
      - patch
  - apiGroups:
    - security.istio.io
    resources:
    - authorizationpolicies
    verbs:
    - list
    - get
    - create
    - delete
